article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
